version: 3.0.{build}

branches:
  only:
  - master

skip_commits:
  files:
    - README.md

image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  EnableNuGetPackageRestore: true
  COVERALLS_REPO_TOKEN:
    secure: kfcmRAw41jRIeZy0b3LGfpsvSleVQYOxXLWS/uMRdzbSljRiq53XrEfubWxlUbmi

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  account_feed: true
  project_feed: true

before_build:
  - cmd: echo Performing NuGet Restore
  - cmd: appveyor-retry nuget restore -verbosity detailed

build:
  project: CodeBlueDev.PluralSight.Core.Models.sln
  parallel: true
  verbosity: detailed
  publish_nuget: true

test_script:
- ps: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[CodeBlueDev*]*" -target:"packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" -targetargs:"--domain=single  Source\CodeBlueDev.PluralSight.Core.Models.Test\bin\Release\CodeBlueDev.PluralSight.Core.Models.Test.dll" -output:coverage.xml
- ps: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%

after_test:
- cmd: nuget pack CodeBlueDev.PluralSight.Core.Models.nuspec

artifacts:
- path: CodeBlueDev.PluralSight.Core.Models.*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: YQjExjfMtx5yNmmDujMicRaII0yUfSnfzVOEqg36o5kLAoVXV4rDetRSseTeO7H5
  artifact: /.*CodeBlueDev.*\.nupkg/