version: x.x.{build}

branches:
  only:
    - master

skip_commits:
  files:
    - README.md

image: Visual Studio 2015

configuration: Release

environment:
  COVERALLS_REPO_TOKEN:
    secure: kfcmRAw41jRIeZy0b3LGfpsvSleVQYOxXLWS/uMRdzbSljRiq53XrEfubWxlUbmi

before_build:
  - cmd: appveyor-retry nuget restore

build:
  project: CodeBlueDev.PluralSight.Core.Models.sln
  parallel: true
  verbosity: normal

test_script:
- ps: >-
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.5.0\tools\nunit3-console.exe" -targetargs:" --domain=single  Source\CodeBlueDev.PluralSight.Core.Models.Test\bin\Release\CodeBlueDev.PluralSight.Core.Models.Test.dll" -output:coverage.xml
    .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml