version: x.x.{build}

branches:
  only:
    - master

skip_commits:
  files:
    - README.md

image: Visual Studio 2017

configuration: Release

environment:
  COVERALLS_REPO_TOKEN:
    secure: kfcmRAw41jRIeZy0b3LGfpsvSleVQYOxXLWS/uMRdzbSljRiq53XrEfubWxlUbmi

before_build:
  - cmd: ECHO Performing NuGet Restore
  - cmd: appveyor-retry nuget restore

build:
  project: CodeBlueDev.PluralSight.Core.Models.sln
  parallel: true
  verbosity: normal
  publish_nuget: true

test_script:
- ps: >-
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.5.0\tools\nunit3-console.exe" -targetargs:" --domain=single  Source\CodeBlueDev.PluralSight.Core.Models.Test\bin\Release\CodeBlueDev.PluralSight.Core.Models.Test.dll" -output:coverage.xml
- ps: >-
    .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

after_test:
  - cmd: nuget pack CodeBlueDev.PluralSight.Core.Models.nuspec

artifacts:
  - path: CodeBlueDev.PluralSight.Core.Models.*.nupkg

deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: yx4NC9MGigYes63ckSkAysWgcYTmpbhe0ZDb9HeO4THEMdbi1gKuI07QxijiuIRK
  artifact: /.*CodeBlueDev.*.nupkg/